import { Cast, Model, type BuilderFor } from "@mahiframework/database";
import { snowflake } from "@mahiframework/snowflake";
import type { DateTime } from "@mahiframework/datetime";

/**
 * One stored file: an avatar, a logo, an invoice PDF, a video.
 *
 * Named `MediaFile` rather than `Media` because every row *is* a file —
 * it has a path, a size, a mime type and a checksum — and because
 * `media` as a bare noun is a collective, which makes `Media.find(id)`
 * returning a single row read wrong. The table stays `media`: it is the
 * collection, the same relationship `ActivityLog` has with
 * `activity_logs`. `Media` is the facade.
 *
 * A row may be owned polymorphically (`model_type`/`model_id`, set by
 * `hasManyMedia`/`hasOneMedia`) or referenced by a foreign key on the
 * owner's own table (`users.avatar_id`, set by `belongsToMedia`). In the
 * second case BOTH morph columns stay null, because the owner is the one
 * holding the reference. That is why they are nullable, and why a row
 * reached only through such a key cannot be found by owner.
 */
export interface MediaFileAttributes {
  /** A snowflake, hence `bigint`: a 64-bit id does not fit a `number`. */
  id: bigint;

  /**
   * The owning model's `morphAlias()`, or null for a `belongsToMedia`
   * row whose owner holds the foreign key instead.
   */
  model_type: string | null;

  /**
   * The owning model's key, stringified.
   *
   * TEXT, not `bigInteger`, which is the one place this schema diverges
   * from `permissions`. There `model_id` is the local side of a
   * `morphToMany` pivot whose key is bound raw, so a `bigint` against a
   * `varchar` makes Postgres raise `operator does not exist` — it has no
   * choice. Nothing here does that: the column is only read back by
   * equality through `morphMany` eager loading, which stringifies both
   * sides. Text therefore holds every key type losslessly and ANY model
   * can own media, which is what a multipurpose package owes its
   * callers. Same column and same reasoning as
   * `notifications.notifiable_id`.
   */
  model_id: string | null;

  /** A logical bucket within one owner: `"photos"`, `"attachments"`. */
  collection: string | null;

  /**
   * The storage disk, or null for "whatever the default disk is now".
   *
   * Null rather than the default's resolved name, so a row written
   * before a `storage.default` change still reads from the current
   * default — `Storage.disk(undefined)` resolves at read time. A row
   * that must pin one disk names it.
   */
  disk: string | null;

  /** Disk-relative path, including the extension. Never user-supplied. */
  path: string;

  /**
   * The name the file had when it arrived, used for downloads and zip
   * entries.
   *
   * Deliberately NOT part of `path`. Keeping a user-supplied name off
   * the filesystem is what stops `../../etc/passwd` and friends from
   * ever being a question, and it means two users uploading `photo.jpg`
   * do not collide.
   */
  original_filename: string;

  /**
   * Size in bytes of the file as stored, after any modifiers ran.
   *
   * A `number`, though the column is an `unsignedBigInteger` and the
   * driver hands back a `bigint`. `Cast.integer()` narrows it, because
   * `JSON.stringify` throws on a `bigint` — deliberately — and a media
   * row is exactly the thing an application serialises into an API
   * response. The precision lost is above 2^53 bytes, which is nine
   * petabytes in one file.
   */
  size: number;

  /** Sniffed from the file's leading bytes, never from the client. */
  mime_type: string;

  /** No leading dot. May be `""` for a file with no discernible type. */
  extension: string;

  checksum_hash: string;
  /** The algorithm `checksum_hash` was produced with, e.g. `"sha256"`. */
  checksum_algo: string;

  /** Pixel dimensions, for images only. Null for every other type. */
  image_width: number | null;
  image_height: number | null;

  /** Position within a collection. 1-indexed; 0 means unordered. */
  order: number;

  /** Application-defined metadata: alt text, captions, EXIF. */
  custom_properties: Record<string, unknown> | null;

  created_at: DateTime;
  updated_at: DateTime;
}

/**
 * The `media` table's model.
 *
 * `keyType: snowflake()` makes this a hard runtime dependency on
 * `SnowflakeServiceProvider`, not just a compile-time one: the key is
 * generated by resolving `SNOWFLAKE_TOKEN`, so an app that omits the
 * provider gets `BindingNotFoundError` on its first upload rather than
 * at boot. The provider's docstring lists it as an ordering constraint
 * and the test harness registers the real thing rather than stubbing
 * ids, so the requirement stays visible.
 *
 * `morphName` is not decoration. `morphAlias()` otherwise falls back to
 * the table name, and the queue codec throws at dispatch for a `Model`
 * field on a job whose class has none.
 *
 * Reads and writes inside this package go through `mediaModels.media`,
 * never through this class directly, so an application can swap in a
 * subclass. See `models/registry.ts`.
 */
export class MediaFile extends Model<MediaFileAttributes>()({
  table: "media",
  primaryKey: "id",
  keyType: snowflake(),
  morphName: "MediaFile",
  casts: {
    // `size` is an `unsignedBigInteger`, so the driver returns a
    // `bigint`. See the attribute's docstring for why it must not stay
    // one.
    size: Cast.integer(),
    custom_properties: Cast.json<Record<string, unknown>>(),
    created_at: Cast.datetime(),
    updated_at: Cast.datetime(),
  },
}) {
  /**
   * Every file owned by one record, in collection order.
   *
   * Pass `Post.morphAlias()` rather than a literal, so a later morph-map
   * change moves both sides at once.
   */
  static for(
    modelType: string,
    modelId: string | number | bigint,
  ): BuilderFor<MediaFileAttributes, MediaFile> {
    return this.query()
      .where("model_type", modelType)
      .where("model_id", String(modelId))
      .orderBy("order", "asc");
  }

  /** One collection across every owner, in collection order. */
  static inCollection(collection: string): BuilderFor<MediaFileAttributes, MediaFile> {
    return this.query().where("collection", collection).orderBy("order", "asc");
  }
}
